baseURL = "https://gideonlabs.com/"
languageCode = "en-us"
title = "Gideon Labs"
publishDir = "../public"
enableRobotsTXT = true
theme = "mainroad"

[taxonomies]
  category = "categories"

[Params]
  description = "We solve problems for the electronic industry using failure analysis, electrical testing, process evaluation and testing to many specifications." # Description of your site
  readmore = false # Show "Read more" button in list if true
  post_navigation = true
  post_meta = ["date", "categories"] # Order of post meta information

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
