baseURL = "https://gideonlabs.com/"
enableRobotsTXT = true
languageCode = "en-us"
publishDir = "../public"
theme = "mainroad"
title = "Gideon Labs"
[Params]
description = "We solve problems for the electronic industry using failure analysis, electrical testing, process evaluation and testing to many specifications."
post_meta = ["date", "categories"]
post_navigation = true
readmore = false
[Params.sidebar]
home = "right"
list = "right"
single = "right"
widgets = ["recent", "categories"]
[Params.widgets]
recent_num = 5
tags_counter = false
[taxonomies]
category = "categories"
