name: Node CI

on:
  push:
    paths:
      - 'hugo/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Hugo
        run: sudo snap install hugo --channel=extended
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v1-${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy:production -- --token ${{ secrets.FIREBASE_TOKEN }}
