name: Node CI

on:
  push:
    paths:
      - 'hugo/**'
      - '.github/workflows/deploy-hugo.yml'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - run: cd hugo && hugo --minify
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: gideonlabs-b4b71
          target: production
