name: Node CI

on:
  push:
    paths:
      - 'hugo/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - run: |
          curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest \
          | grep browser_download_url \
          | grep Linux-64bit.deb \
          | grep extended \
          | cut -d '"' -f 4 \
          | wget -i -
          sudo dpkg -i hugo*_Linux-64bit.deb
      - run: cd hugo && hugo --minify
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: gideonlabs-b4b71
